### ISSUE TITLE
Non descriptive text for Widget Title setting

### ISSUE THREAD

**Issue by defries** [ThemeMix/thememix-pro-genesis#10]
<img alt="widgets_ _genesis_test_site_ _wordpress" src="https://cloud.githubusercontent.com/assets/411524/14427800/abdc5fbc-fff6-11e5-9ec2-784149bad8e6.png">
Right now this looks confusing. I think the easiest way is to change the text to something like this: `Would you like to link the Widget title to a link?`

**Comment by ryanhellyer** [comment]
Perhaps `Add widget title link` would be a better option?

Your text refers to linking to a link, which doesn't sound correct.

**Comment by defries** [comment]
`Would you like to link the Widget title to a URL?`

**Comment by ryanhellyer** [comment]
That works. Change is now in develop.
