### ISSUE TITLE
Optimize Settings improvements

### ISSUE THREAD

**Issue by defries** [ThemeMix/thememix-pro-genesis#12]
Unless the checkbox is actually checked, the rest of the Optimize setting should be visible
<img alt="widgets_ _genesis_test_site_ _wordpress" src="https://cloud.githubusercontent.com/assets/411524/14428031/8d88e61a-fff7-11e5-97af-54bcc87ff6dc.png">

Related #11

**Comment by ryanhellyer** [comment]
This has been implemented in the develop branch.
