### ISSUE TITLE
Featured Content widget title link issue

### ISSUE THREAD

**Issue by defries** [ThemeMix/thememix-pro-genesis#23]
When you select a custom URL at the second arrow:
![link-issue](https://cloud.githubusercontent.com/assets/411524/16196159/27763912-36fd-11e6-847a-1046d08fc7ed.png)
I expect that link to be used for 
* [x] the post/page title as well as 
* [x] the content/excerpt/content-limit selected below. 

Neither is happening right now. 
Even worse, the link currently is bleeding to HTML items below as can be seen [my frontpage right now](https://remkusdevries.com).

**Comment by ryanhellyer** [comment]
A fix for this has been added to the development branch, ready for the next release.

**Comment by defries** [comment]
Are both items, as listed in the issue, fixed? If so, please check them.

**Comment by ryanhellyer** [comment]
There were no tick boxes when I looked before. Both boxes are now ticked.

There was a bug anyway, so I had reopened it to fix that.

**Comment by defries** [comment]
Wonderful.
