### ISSUE TITLE
Featured Content Widget - Font awesome icon

### ISSUE THREAD

**Issue by ryanhellyer** [ThemeMix/thememix-pro-genesis#3]
It should be possible to select a font awesome icon and choose where it is ouputted.

eg: https://wordpress.org/plugins/wp-term-icons/

We should add a sizeand colour option to allow users to adjust the icon.

Possible positions:
* Before title (centered)
* Inline before title
* Inline after title
* After title (centered)

**Comment by ryanhellyer** [comment]
Use the UI from wp-term-icons for the backend.

**Comment by ryanhellyer** [comment]
It may be possible to scrape the Font Awesome Icons via this ... 
https://github.com/forsitemedia/fortytwo/blob/develop/Gruntfile.js#L118

**Comment by ryanhellyer** [comment]
Selector from WP Term Icons uses this ... https://github.com/bradvin/dashicons-picker/

**Comment by ryanhellyer** [comment]
The dashicons-picker script works perfectly everywhere I try it, except for inside a widget. I'm going to tackle this again after I've done some other tasks.

**Comment by ryanhellyer** [comment]
The size and position of the icon has now been set. The colour picker has been partially implemented, but requires some further work.

**Comment by ryanhellyer** [comment]
Is it okay if this uses dashicons instead of Font Awesome? After implementing it, I've now found out that the library used in the plugin this was based on (linked in the initial ticket post) uses dashicons, not Font Awesome. It worked, but it turns out this was only dumb luck due to some of the icon names matching up. Most of them failed. I have put together feature/dashicons-3 which converts it to use dashicons, which will be simpler than trying to get Font Awesome working instead.

**Comment by defries** [comment]
Has to be Font Awesome. In fact, we need to implement a way to autogenerate
the list of available fonts. I think I mentioned this somewhere else, right?
