### ISSUE TITLE
Featured Content Widget - BuddyPress group

### ISSUE THREAD

**Issue by ryanhellyer** [ThemeMix/thememix-pro-genesis#4]
Should be able to select a BuddyPress Group (as if you were to select a page)

**Comment by ryanhellyer** [comment]
Once a BuddyPress group is selected, what should it change in the actual widget output?

Is it perhaps meant to display a BuddyPress activity?

**Comment by defries** [comment]
Correct. Display the set amount of activity entries.

**Comment by ryanhellyer** [comment]
Making this widget display BuddyPress group activity is quite awkward. The widget is designed with displaying posts in mind, whereas BuddyPress activities are something different.

My current plan involves a rather time consuming approach of basically building a separate widget to display when the BuddyPress group activity mode is turned on. I'm going to drop this in the interim and tackle it again later. I may stumble across an easier way of implementing it whilst working on other things in the plugin.
