### ISSUE TITLE
Featured Content Widget - Column grid

### ISSUE THREAD

**Issue by ryanhellyer** [ThemeMix/thememix-pro-genesis#5]
Should be able to select a column grid for the output of the widget.

eg: http://www.simpleprothemes.com/flex/

**Comment by ryanhellyer** [comment]
Is this the intended outcome?

![column-grid-front](https://cloud.githubusercontent.com/assets/430544/12918533/f7fd90f6-cf3f-11e5-9b83-8c7cc5cdc19e.png)
![column-grid-admin](https://cloud.githubusercontent.com/assets/430544/12918534/f818597c-cf3f-11e5-9a3b-79492112728d.png)

**Comment by defries** [comment]
Yes, but a full page wide widget area with some more content (+ content +
image) would make it easier to tell.

>
