### ISSUE TITLE
Font Icon selector doesn't work

### ISSUE THREAD

**Issue by defries** [ThemeMix/thememix-pro-genesis#8]
When you check to want to include the Font Icon Selector, nothing happens.

**Comment by ryanhellyer** [comment]
This didn't make sense to me initially. But it seems it does work when you refresh the page, but not you click the checkbox to display it immediately before trying to add it.

**Comment by ryanhellyer** [comment]
The Background Color is not saving either.

**Comment by ryanhellyer** [comment]
I am not managing to fix the Font Icon selector bug.

I can make it work on loading the widget by using an external script, and I can make it work on toggling the checkbox by using an inline script. But I can't make it work both on initial page load and on toggling the checkbox. This seems to have something to do with how it's loading the HTML dynamically each time the checkbox is toggled, but I'm unsure how to work around it.

**Comment by ryanhellyer** [comment]
This bug is also triggered on saving. So removing the "required" checkbox does not totally avoid the problem unfortunately.

**Comment by barrykooij** [comment]
I think this is because the element is created dynamically and you're probably binding the onclick on document.ready/body.load. So when you bind the event, the element doesn't exist yet.

Something like this should work:

```
<script type="text/javascript">
					jQuery( function ( $ ) {
						$( '.YOUR-WIDGET-CLASS' ).on( 'click', '.FONT-AWESOME-BUTTON', function ( event ) {
							alert( 'Remkus is gek' );
						} );
					} );
				</script>
```

**Comment by ryanhellyer** [comment]
Thanks @barrykooij :)

I'm also fairly sure it's caused by the elements being added dynamically, but I didn't realise it was due to binding issues.

Are you able to see where it's bound here?
https://github.com/ThemeMix/thememix-pro-genesis/blob/master/modules/featured-content-widget/font-awesome/js/font-awesome-picker.js

**Comment by barrykooij** [comment]
Do you know why the unbind is here btw? https://github.com/ThemeMix/thememix-pro-genesis/blob/master/modules/featured-content-widget/font-awesome/js/font-awesome-picker.js#L710

**Comment by ryanhellyer** [comment]
> aka if you comment that out, does that fix the issue?

No, unfortunately it does not.

**Comment by ryanhellyer** [comment]
There is another reference to bind here, but removing that section of code does not seem to have any affect.

https://github.com/ThemeMix/thememix-pro-genesis/blob/master/modules/featured-content-widget/font-awesome/js/font-awesome-picker.js#L701

I also tried changing it to this, but that did not help either:
```$( 'input[type=text].fontawesome-picker' ).on( 'click', 'button.fontawesome-picker', function ( event ) {```
