### ISSUE TITLE
Column widget settings are confusing

### ISSUE THREAD

**Issue by defries** [ThemeMix/thememix-pro-genesis#9]
<img alt="widgets_ _genesis_test_site_ _wordpress" src="https://cloud.githubusercontent.com/assets/411524/14427748/62c2d87e-fff6-11e5-92eb-a3ac7379591c.png">
The following is confusing. What sets what and shouldn't those two column related settings be combined?

**Comment by ryanhellyer** [comment]
They are now combined in the develop branch.
